# Generated by Django 5.1.7 on 2025-04-04 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oder',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='Oder_item',
            new_name='Order_item',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order_item',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order_item',
            old_name='oder_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
