# Generated by Django 5.1.7 on 2025-04-04 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_oder_order_rename_oder_item_order_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product'),
        ),
    ]
