# Generated by Django 5.1.7 on 2025-05-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_size',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
