# Generated by Django 5.1.7 on 2025-05-14 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_product_size_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_size',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_sizes', to='app.product'),
        ),
    ]
