# Generated by Django 5.1.7 on 2025-05-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_product_size_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'thanh toán khi nhận hàng'), ('ONLINE', 'thanh toán trực tuyến')], default='COD', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('CONFIRMED', 'Đã xác nhận'), ('DELIVERED', 'Đã giao'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20),
        ),
    ]
