# Generated by Django 5.1.7 on 2025-05-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_order_shipping_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product_size',
            unique_together={('product', 'size')},
        ),
    ]
