# Generated by Django 5.1.7 on 2025-06-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_product_size_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_size',
            name='status',
            field=models.CharField(choices=[('in', 'Còn hàng'), ('out', 'Hết hàng')], default='in', max_length=10),
        ),
    ]
