# Generated by Django 5.1.7 on 2025-06-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thongtingiaovien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('chuyennganh', models.CharField(max_length=10, null=True)),
                ('tuoi', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
