# Generated by Django 5.1.7 on 2025-07-14 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_color_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.color'),
        ),
    ]
